strategy: MNQ808
params:
  atr_mult: 1.5
  lookback: 10
  use_mfi: true
  trail_mult_legacy: 1.0
  contracts: 1
  risk_ticks_legacy: 150
  session_start: "08:00"
  session_end: "16:30"
  tick_size: 0.25
  tick_value: 0.5
  treat_atr_as_ticks: true
data:
  path: crossover_test_data.csv
  timeframe: "15m"
eval:
  walkforward:
    kind: "sliding"
    train_bars: 20   # Reduced for testing
    test_bars: 10    # Reduced for testing
fees_bps: 1.0
slippage_bps: 1.0
seed: 42